### ISSUE TITLE
Double Click Tray Icon does not restore window

### ISSUE THREAD

**Issue by mckinnon81** [Spyna/teams-for-linux#2]
Desktop: Cinnamon

When double clicking on Tray Icon it does not restore Teams Window. You have to right click Icon and select Open

**Comment by Spyna** [comment]
Unfortunately on Linux, as far as I know, there is no way to listen to the `double-click` event. 
https://electronjs.org/docs/api/tray#instance-events

**Comment by mckinnon81** [comment]
Looks like others have found a way to do this in Electron.

You can see how they did it here - https://github.com/zulip/zulip-electron/pull/529

Looks like a rewrite of the Tray.js may be needed to get it to work.
